spring:
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 500MB
      max-request-size: 500MB

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/oes_db?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
      username: root
      password: xujian123
      # 连接池配置
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
      # 监控配置
      filters: stat,wall # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      aop-patterns: org.oes.biz.service.*      #Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
      web-stat-filter:      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
        principal-session-name: session_name
        principal-cookie-name: cookie_name
        profile-enable:
      stat-view-servlet:      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置默认false
        enabled: true
        url-pattern: /druid/*        # 配置DruidStatViewServlet
        reset-enable: false        #  禁用HTML页面上的“Reset All”功能
        login-username: admin        # 监控页面登录的用户名
        login-password: 123456        # 监控页面登录的密码
        allow: 127.0.0.1        #IP白名单(没有配置或者为空，则允许所有访问)
        deny:        #IP黑名单 (存在共同时，deny优先于allow)

  redis:
    # Redis数据库索引（默认为 0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 5000

  # 邮件设置
  mail:
    host: smtp.qq.com
    username: 941197279@qq.com
    password: rpsvmiypfnocbfgi
    default-encoding: utf-8

# 系统常量配置
oes:
  env: dev
  enable-redis-cache: true
  shiro:
    session-timeout: 3600   # session 超时时间，单位为秒
    cookie-timeout: 864000  # rememberMe cookie有效时长，单位为秒
  minio:
    endpoint: http://124.222.228.84:8081
    root-user: oesminio
    root-password: oesminioadmin
