server:
  port: 8089    # tomcat端口号
  servlet:
    context-path: /     # 根路径
    encoding:    # 编码集设置
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: dev

  application:
    name: oes    # 项目名称

# mybatis映射文件路径配置
mybatis:
  type-aliases-package: org.oes.biz.entity
  mapper-locations: classpath:mapper/*.xml

# 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql